#!/usr/bin/env python
import RPi.GPIO as GPIO
import time
import numpy as np

GPIO.setmode(GPIO.BOARD)
GPIO.setup(03, GPIO.OUT)
pwm = GPIO.PWM(03,50)
pwm.start(0)

for duty in np.linspace(0, 15, 1000):
	pwm.ChangeDutyCycle(duty)
	print(duty)
	time.sleep(0.1)

